### PR TITLE
Create PoleMaster_0.1.py

### PR DESCRIPTION
**Pull request by mazlow17**
PoleMasterCode Beta Progression

### CODE REVIEW

**Comment by jmm8046** [comment]
Are we sure we want to combine this onto the scanner repo and not have it as it's own repo? Open to thoughts for either choice

**Comment by david-samuel-mcdermott** [comment]
@jmm8046 You want two repos - if these codebases don't touch, you want two separate repos unless you have a good reason to have them in one - it will get confusing and it lets you hint where people can work easier (this is like 90% C++ the other repo would be like 90% Python)

**Comment by jmm8046** [comment]
@david-samuel-mcdermott Yep! We already made a different repo and just forgot to close this PR

**Comment by david-samuel-mcdermott** [comment]
Okay, let's do that then

**Pull request closed without merging**
